flowgraph:
  r-htmlPath-strict:
    - $
  r-jspPath-strict:
    - $
  r-viewPathHtml:
    - $
  r-viewPathJsp:
    - $
  r-htmlPath-slash:
    - $
  r-jspPath-slash:
    - $
  r-viewPathHtml-slash:
    - $
  r-viewPathJsp-slash-strict:
    - $
  r-modelMap:
    - r-htmlPath-strict
    - r-jspPath-strict
    - r-viewPathHtml
    - r-viewPathJsp
    - r-htmlPath-slash
    - r-jspPath-slash
    - r-viewPathHtml-slash
    - r-viewPathJsp-slash-strict
  r-setAttr:
    - r-htmlPath-strict
    - r-viewPathHtml
    - r-htmlPath-slash
    - r-viewPathHtml-slash
  r-setAttrJsp:
    - r-jspPath-strict
    - r-viewPathJsp
    - r-jspPath-slash
    - r-viewPathJsp-slash-strict
  r-addAttr:
    - r-htmlPath-strict
    - r-viewPathHtml
    - r-htmlPath-slash
    - r-viewPathHtml-slash
  r-addAttrJsp:
    - r-jspPath-strict
    - r-viewPathJsp
    - r-jspPath-slash
    - r-viewPathJsp-slash-strict
  r-global-model:
    - r-htmlPath-strict
    - r-viewPathHtml
    - r-htmlPath-slash
    - r-viewPathHtml-slash
  r-getAttr:
    - r-htmlPath-strict
    - r-viewPathHtml
  r-getAttrJsp:
    - r-jspPath-strict
    - r-viewPathJsp
  r-global-model-jsp:
    - r-jspPath-strict
    - r-viewPathJsp
  r-setAttr-dot:
    - r-htmlPath-strict
    - r-viewPathHtml
  r-setAttrJsp-dot:
    - r-jspPath-strict
    - r-viewPathJsp
  r-addAttr-dot:
    - r-htmlPath-strict
    - r-viewPathHtml
  r-addAttrJsp-dot:
    - r-jspPath-strict
    - r-viewPathJsp
  r-getAttr-dot:
    - r-htmlPath-strict
    - r-viewPathHtml
  r-getAttrJsp-dot:
    - r-jspPath-strict
    - r-viewPathJsp
  r-global-model-dot:
    - r-htmlPath-strict
    - r-viewPathHtml
  r-global-model-jsp-dot:
    - r-jspPath-strict
    - r-viewPathJsp
  r-setAttr-blank:
    - r-htmlPath-strict
    - r-viewPathHtml
  r-setAttrJsp-blank:
    - r-jspPath-strict
    - r-viewPathJsp
  r-addAttr-blank:
    - r-htmlPath-strict
    - r-viewPathHtml
  r-addAttrJsp-blank:
    - r-jspPath-strict
    - r-viewPathJsp
  r-getAttr-blank:
    - r-htmlPath-strict
    - r-viewPathHtml
  r-getAttrJsp-blank:
    - r-jspPath-strict
    - r-viewPathJsp
  r-global-model-blank:
    - r-htmlPath-strict
    - r-viewPathHtml
  r-global-model-jsp-blank:
    - r-jspPath-strict
    - r-viewPathJsp
  r-modelMap-put:
    - r-modelMap
  r-modelMap-put-jsp:
    - r-modelMap
  r-modelMap-put-dot:
    - r-modelMap
  r-modelMap-put-jsp-dot:
    - r-modelMap
  r-modelMap-put-blank:
    - r-modelMap
  r-modelMap-put-jsp-blank:
    - r-modelMap
  r-mav-htmlPath:
    - $
  r-mav-modelName:
    - r-mav-htmlPath
  r-mav-attr:
    - r-mav-modelName
  r-mav-attr-dot:
    - r-mav-modelName
  r-mav-attr-blank:
    - r-mav-modelName

rules:
  # model.addAttribute("name", ) <-> ${name}
  r-addAttr:
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: '(&functionName)/*addAttribute'
      inline:
        identifier: (name:snake)
    use:
      lang: HTML
      file: (&htmlFile).html
      identifier: "**"
      inline:
        identifier: "${(name:snake)}"

  r-addAttr-dot:
    hidden: true
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: '(&functionName)/*addAttribute'
      inline:
        identifier: (name:snake)
    use:
      lang: HTML
      file: (&htmlFile).html
      identifier: "**"
      inline:
        identifier: "${(name:snake).*}"

  r-addAttr-blank:
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: '(&functionName)/*addAttribute'
      inline:
        identifier: (name:snake)
    use:
      lang: HTML
      file: (&htmlFile).html
      identifier: "**"
      inline:
        identifier: "${(name:snake) }"

  r-addAttrJsp:
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: '(&functionName)/*addAttribute'
      inline:
        identifier: (name:snake)
    use:
      lang: HTML
      file: (&jspFile).jsp
      identifier: "**"
      inline:
        identifier: "${(name:snake)}"

  r-addAttrJsp-dot:
    hidden: true
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: '(&functionName)/*addAttribute'
      inline:
        identifier: (name:snake)
    use:
      lang: HTML
      file: (&jspFile).jsp
      identifier: "**"
      inline:
        identifier: "${(name:snake).*}"

  r-addAttrJsp-blank:
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: '(&functionName)/*addAttribute'
      inline:
        identifier: (name:snake)
    use:
      lang: HTML
      file: (&jspFile).jsp
      identifier: "**"
      inline:
        identifier: "${(name:snake) }"

  # model.addAttribute("name", ) <-> ${name}
  r-setAttr:
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: '(&functionName)/*setAttribute'
      inline:
        identifier: (name:snake)
    use:
      lang: HTML
      file: (&htmlFile).html
      identifier: "**"
      inline:
        identifier: "${(name:snake)}"

  r-setAttr-dot:
    hidden: true
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: '(&functionName)/*setAttribute'
      inline:
        identifier: (name:snake)
    use:
      lang: HTML
      file: (&htmlFile).html
      identifier: "**"
      inline:
        identifier: "${(name:snake).*}"

  r-setAttr-blank:
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: '(&functionName)/*setAttribute'
      inline:
        identifier: (name:snake)
    use:
      lang: HTML
      file: (&htmlFile).html
      identifier: "**"
      inline:
        identifier: "${(name:snake) }"

  r-setAttrJsp:
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: '(&functionName)/*setAttribute'
      inline:
        identifier: (name:snake)
    use:
      lang: HTML
      file: (&jspFile).jsp
      identifier: "**"
      inline:
        identifier: "${(name:snake)}"

  r-setAttrJsp-dot:
    hidden: true
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: '(&functionName)/*setAttribute'
      inline:
        identifier: (name:snake)
    use:
      lang: HTML
      file: (&jspFile).jsp
      identifier: "**"
      inline:
        identifier: "${(name:snake).*}"

  r-setAttrJsp-blank:
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: '(&functionName)/*setAttribute'
      inline:
        identifier: (name:snake)
    use:
      lang: HTML
      file: (&jspFile).jsp
      identifier: "**"
      inline:
        identifier: "${(name:snake) }"


  r-getAttr:
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: '(&functionName)/*getParameter'
      inline:
        identifier: (name:snake)
    use:
      lang: HTML
      file: (&htmlFile).html
      identifier: "**"
      inline:
        identifier: "${(name:snake)}"

  r-getAttr-dot:
    hidden: true
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: '(&functionName)/*getAttribute'
      inline:
        identifier: (name:snake)
    use:
      lang: HTML
      file: (&htmlFile).html
      identifier: "**"
      inline:
        identifier: "${(name:snake).*}"

  r-getAttr-blank:
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: '(&functionName)/*getAttribute'
      inline:
        identifier: (name:snake)
    use:
      lang: HTML
      file: (&htmlFile).html
      identifier: "**"
      inline:
        identifier: "${(name:snake) }"

  r-getAttrJsp:
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: '(&functionName)/*getAttribute'
      inline:
        identifier: (name:snake)
    use:
      lang: HTML
      file: (&jspFile).jsp
      identifier: "**"
      inline:
        identifier: "${(name:snake)}"

  r-getAttrJsp-dot:
    hidden: true
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: '(&functionName)/*getAttribute'
      inline:
        identifier: (name:snake)
    use:
      lang: HTML
      file: (&jspFile).jsp
      identifier: "**"
      inline:
        identifier: "${(name:snake).*}"

  r-getAttrJsp-blank:
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: '(&functionName)/*getAttribute'
      inline:
        identifier: (name:snake)
    use:
      lang: HTML
      file: (&jspFile).jsp
      identifier: "**"
      inline:
        identifier: "${(name:snake) }"

  # functionName(ModelMap modelName) <-> modelName.put("name", )
  # optional
  r-modelMap:
    hidden: true
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: "(&functionName)/**/(modelMap)"
      varType: ModelMap
    use:
      lang: JAVA
      file: (&javaFile).java
      identifier: (&functionName)/(modelMap).put


  r-modelMap-put:
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: "(&functionName)/**/(&modelMap).put"
      inline:
        identifier: (name:snake)
    use:
      lang: HTML
      file: (&htmlFile).html
      identifier: "**"
      inline:
        identifier: "${(name:snake)}"

  r-modelMap-put-jsp:
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: "(&functionName)/**/(&modelMap).put"
      inline:
        identifier: (name:snake)
    use:
      lang: HTML
      file: (&jspFile).jsp
      identifier: "**"
      inline:
        identifier: "${(name:snake)}"

  r-modelMap-put-dot:
    hidden: true
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: "(&functionName)/**/(&modelMap).put"
      inline:
        identifier: (name:snake)
    use:
      lang: HTML
      file: (&htmlFile).html
      identifier: "**"
      inline:
        identifier: "${(name:snake).*}"

  r-modelMap-put-jsp-dot:
    hidden: true
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: "(&functionName)/**/(&modelMap).put"
      inline:
        identifier: (name:snake)
    use:
      lang: HTML
      file: (&jspFile).jsp
      identifier: "**"
      inline:
        identifier: "${(name:snake).*}"

  r-modelMap-put-blank:
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: "(&functionName)/**/(&modelMap).put"
      inline:
        identifier: (name:snake)
    use:
      lang: HTML
      file: (&htmlFile).html
      identifier: "**"
      inline:
        identifier: "${(name:snake) }"

  r-modelMap-put-jsp-blank:
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: "(&functionName)/**/(&modelMap).put"
      inline:
        identifier: (name:snake)
    use:
      lang: HTML
      file: (&jspFile).jsp
      identifier: "**"
      inline:
        identifier: "${(name:snake) }"

  # return "htmlPath" <-> htmlPath.html
  r-htmlPath:
    use:
      lang: JAVA
      file: (root...)/src/main/**/(javaFile).java
      identifier: (functionName)/return/**
      inline:
        identifier: (htmlFile...)
    def:
      lang: FILE
      file: (root...)/src/main/(htmlFile...).html

  r-htmlPath-strict:
    use:
      lang: JAVA
      file: (root...)/src/main/**/(javaFile).java
      identifier: (functionName)/return/**
      inline:
        identifier: (htmlFile...)
    def:
      lang: FILE
      file: (root...)/src/main/(htmlFile...).html

  r-htmlPath-slash:
    use:
      lang: JAVA
      file: (root...)/src/main/**/(javaFile).java
      identifier: (functionName)/return/**
      inline:
        identifier: \/(htmlFile...)
    def:
      lang: FILE
      file: (root...)/src/main/(htmlFile...).html

  r-jspPath:
    use:
      lang: JAVA
      file: (root...)/src/main/**/(javaFile).java
      identifier: (functionName)/return/**
      inline:
        identifier: (jspFile...)
    def:
      lang: FILE
      file: (root...)/src/main/(jspFile...).jsp

  r-jspPath-strict:
    use:
      lang: JAVA
      file: (root...)/src/main/**/(javaFile).java
      identifier: (functionName)/return/**
      inline:
        identifier: (jspFile...)
    def:
      lang: FILE
      file: (root...)/src/main/(jspFile...).jsp

  r-jspPath-slash:
    use:
      lang: JAVA
      file: (root...)/src/main/**/(javaFile).java
      identifier: (functionName)/return/**
      inline:
        identifier: \/(jspFile...)
    def:
      lang: FILE
      file: (root...)/src/main/(jspFile...).jsp

  r-viewPathHtml:
    use:
      lang: JAVA
      file: (javaFile).java
      identifier: (functionName)/return/**
      inline:
        identifier: (htmlFile...).html
    def:
      lang: FILE
      file: (htmlFile...).html

  r-viewPathHtml-slash:
    use:
      lang: JAVA
      file: (javaFile).java
      identifier: (functionName)/return/**
      inline:
        identifier: \/(htmlFile...).html
    def:
      lang: FILE
      file: (htmlFile...).html

  r-viewPathJsp:
    use:
      lang: JAVA
      file: (javaFile).java
      identifier: (functionName)/return/**
      inline:
        identifier: (jspFile...).jsp
    def:
      lang: FILE
      file: (jspFile...).jsp

  r-viewPathJsp-slash:
    use:
      lang: JAVA
      file: (root...)/src/main/**/(javaFile).java
      identifier: (functionName)/return/**
      inline:
        identifier: \/(jspFile...).jsp
    def:
      lang: FILE
      file: (root...)/src/main/(jspFile...).jsp

  r-viewPathJsp-slash-strict:
    use:
      lang: JAVA
      file: (root...)/src/main/**/(javaFile).java
      identifier: (functionName)/return/**
      inline:
        identifier: \/(jspFile...).jsp
    def:
      lang: FILE
      file: (root...)/src/main/(jspFile...).jsp

  # mav.setViewName("htmlPath") <-> htmlPath.html
  r-mav-htmlPath:
    use:
      lang: JAVA
      file: (javaFile).java
      identifier: '(mav).setViewName'
      inline:
        identifier: (htmlFile...)
    def:
      lang: FILE
      file: (htmlFile...).html

  r-mav-htmlPath-jsp:
    use:
      lang: JAVA
      file: (javaFile).java
      identifier: '(mav).setViewName'
      inline:
        identifier: (jspFile...)
    def:
      lang: FILE
      file: (jspFile...).jsp

  # functionName(ModelAndView mav) <-> mav.addObject("name", )
  r-mav-modelName:
    hidden: true
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: "(functionName)/(&mav)"
      varType: ModelAndView
    use:
      lang: JAVA
      file: (&javaFile).java
      identifier: (functionName)/(&mav).addObject
      inline:
        identifier: (name:snake)

  # mav.addObject("name", ) <-> ${name}
  r-mav-attr:
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: '(&controller)/(&functionName)/(&mav)/addObject'
      inline:
        identifier: (&name)
    use:
      lang: OTHER
      file: (&htmlFile).html
      identifier: "**"
      inline:
        identifier: "${(&name)}"

  r-mav-attr-dot:
    hidden: true
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: '(&controller)/(&functionName)/(&mav)/addObject'
      inline:
        identifier: (&name)
    use:
      lang: OTHER
      file: (&htmlFile).html
      identifier: "**"
      inline:
        identifier: "${(&name).*}"

  r-mav-attr-blank:
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: '(&controller)/(&functionName)/(&mav)/addObject'
      inline:
        identifier: (&name)
    use:
      lang: OTHER
      file: (&htmlFile).html
      identifier: "**"
      inline:
        identifier: "${(&name) }"

  # @ModelAttribute("name") <-> ${name}
  r-global-model:
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: '(&functionName)/@ModelAttribute'
      inline:
        identifier: (name:snake)
    use:
      lang: OTHER
      file: (&htmlFile).html
      identifier: "**"
      inline:
        identifier: "${(name:snake)}"

  r-global-model-dot:
    hidden: true
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: '(&functionName)/@ModelAttribute'
      inline:
        identifier: (name:snake)
    use:
      lang: OTHER
      file: (&htmlFile).html
      identifier: "**"
      inline:
        identifier: "${(name:snake).*}"

  r-global-model-blank:
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: '(&functionName)/@ModelAttribute'
      inline:
        identifier: (name:snake)
    use:
      lang: OTHER
      file: (&htmlFile).html
      identifier: "**"
      inline:
        identifier: "${(name:snake) }"

  r-global-model-jsp:
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: '(&functionName)/@ModelAttribute'
      inline:
        identifier: (name:snake)
    use:
      lang: OTHER
      file: (&jspFile).jsp
      identifier: "**"
      inline:
        identifier: "${(name:snake)}"

  r-global-model-jsp-dot:
    hidden: true
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: '(&functionName)/@ModelAttribute'
      inline:
        identifier: (name:snake)
    use:
      lang: OTHER
      file: (&jspFile).jsp
      identifier: "**"
      inline:
        identifier: "${(name:snake).*}"

  r-global-model-jsp-blank:
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: '(&functionName)/@ModelAttribute'
      inline:
        identifier: (name:snake)
    use:
      lang: OTHER
      file: (&jspFile).jsp
      identifier: "**"
      inline:
        identifier: "${(name:snake) }"
